spring:
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: pro

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lxy.pojo
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

frontHotSize: 10
frontNewRecommend: 10
frontNewSize: 3

commentAvatar: /images/avatar.jpg
