server:
  port: 8023

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    root: warn
    com.lxy: info
  file:
    name: log/blog-pro.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: blog-pro.%d{yyyy-MM-dd}--%i.log

